name: Generate a build and push to another branch

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install project dependencies
      - name: Install all dependencies
        run: npm install

      # Step 3: Run the build command
      - name: Build
        run: npm run build

      # Step 4: Debugging - List the contents of the project root to verify the `dist` folder
      - name: List directory contents
        run: ls -la # List the contents of the current directory to verify `dist` folder

      # Step 5: Push build artifacts to the 'build' branch
      - name: Push to build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self # This points to the same repository
          BRANCH: build # Branch to push the built files (create if it doesn't exist)
          FOLDER: dist # Directory containing the build artifacts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
          MESSAGE: "Build: ({sha}) {msg}" # Commit message for the build
